### ISSUE TITLE
Error when building qt_gui_cpp

### ISSUE THREAD

**Issue by j4cobgarby** [m2-farzan/ros2-humble-PKGBUILD#4]
I get this error about 25 minutes after running `yay -S ros2-humble`:

```
Starting >>> qt_gui_cpp
--- stderr: qt_gui_cpp                                         
sip: /usr/lib/python3.10/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error
Traceback (most recent call last):
  File "/home/j4cobgarby/.cache/yay/ros2-humble/src/install/share/python_qt_binding/cmake/sip_configure.py", line 123, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip', '-c', '/home/j4cobgarby/.cache/yay/ros2-humble/src/build/qt_gui_cpp/sip/qt_gui_cpp_sip', '-b', '/home/j4cobgarby/.cache/yay/ros2-humble/src/build/qt_gui_cpp/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/usr/lib/python3.10/site-packages/PyQt5/bindings', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_15_0', '-t', 'WS_X11', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:253: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< qt_gui_cpp [12.3s, exited with code 2]

Summary: 145 packages finished [25min 11s]
  1 package failed: qt_gui_cpp
  45 packages had stderr output: ament_clang_format ament_clang_tidy ament_copyright ament_cppcheck ament_cpplint ament_flake8 ament_index_python ament_lint ament_lint_cmake ament_mypy ament_package ament_pclint ament_pep257 ament_pycodestyle ament_pyflakes ament_uncrustify ament_xmllint domain_coordinator fastrtps foonathan_memory_vendor google_benchmark_vendor iceoryx_posh ignition_cmake2_vendor ignition_math6_vendor launch launch_pytest launch_testing launch_xml launch_yaml libyaml_vendor mimick_vendor osrf_pycommon osrf_testing_tools_cpp performance_test_fixture python_orocos_kdl_vendor qt_gui_cpp rosidl_cli rpyutils rti_connext_dds_cmake_module rviz_ogre_vendor shared_queues_vendor test_osrf_testing_tools_cpp tracetools_read tracetools_trace uncrustify_vendor
  194 packages not processed
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: ros2-humble
```

I'm running Arch Linux on Linux 5.19.11, on an x86_64 machine.

**Comment by m2-farzan** [comment]
Hi, sorry for my late response. Please see https://github.com/m2-farzan/ros2-galactic-PKGBUILD/issues/9
